#import <PEGKit/PKParser.h>

enum {
    EXPRESSIONPARSER_TOKEN_KIND_DOLLAR = 14,
    EXPRESSIONPARSER_TOKEN_KIND_PUT,
    EXPRESSIONPARSER_TOKEN_KIND_DOT,
    EXPRESSIONPARSER_TOKEN_KIND_EOL,
    EXPRESSIONPARSER_TOKEN_KIND_VAR,
    EXPRESSIONPARSER_TOKEN_KIND_COLON,
    EXPRESSIONPARSER_TOKEN_KIND_SETVARIABLE,
    EXPRESSIONPARSER_TOKEN_KIND_PERCENT,
    EXPRESSIONPARSER_TOKEN_KIND_SEMI_COLON,
};

@interface ExpressionParser : PKParser
        
    @property (nonatomic, strong) NSMutableArray *tokens;

@end

