#import <PEGKit/PKParser.h>

enum {
    EXPRESSIONPARSER_TOKEN_KIND_MOVE = 14,
    EXPRESSIONPARSER_TOKEN_KIND_COLON,
    EXPRESSIONPARSER_TOKEN_KIND_SEMI_COLON,
    EXPRESSIONPARSER_TOKEN_KIND_DOT,
    EXPRESSIONPARSER_TOKEN_KIND_ECHO,
    EXPRESSIONPARSER_TOKEN_KIND_FORWARD_SLASH,
    EXPRESSIONPARSER_TOKEN_KIND_PAUSE,
    EXPRESSIONPARSER_TOKEN_KIND_PUT,
    EXPRESSIONPARSER_TOKEN_KIND_WAITFORRE,
    EXPRESSIONPARSER_TOKEN_KIND_MATCHWAIT,
    EXPRESSIONPARSER_TOKEN_KIND_NEXTROOM,
    EXPRESSIONPARSER_TOKEN_KIND_DOLLAR,
    EXPRESSIONPARSER_TOKEN_KIND_EXITSTMT,
    EXPRESSIONPARSER_TOKEN_KIND_WAITFOR,
    EXPRESSIONPARSER_TOKEN_KIND_PERCENT,
    EXPRESSIONPARSER_TOKEN_KIND_SETVARIABLE,
    EXPRESSIONPARSER_TOKEN_KIND_MATCHRE,
    EXPRESSIONPARSER_TOKEN_KIND_CARET,
    EXPRESSIONPARSER_TOKEN_KIND_GOTO,
    EXPRESSIONPARSER_TOKEN_KIND_PIPE,
    EXPRESSIONPARSER_TOKEN_KIND_VAR,
    EXPRESSIONPARSER_TOKEN_KIND_MATCH,
};

@interface ExpressionParser : PKParser
        
    @property (nonatomic, strong) NSMutableArray *tokens;
    @property (nonatomic, strong) NSMutableArray *match_tokens;

@end

